### ISSUE TITLE
Fatal Error on restart

### ISSUE THREAD

**Issue by Zeddikiel** [massclown/HalfSwordTrainerMod#1]
While the game is running and started, pressing restart or dying (by holding G or being killed by an enemy) Fatal Errors the game.

**Comment by massclown** [comment]
Which version of the mod are you running? Sadly, crashes happen sometimes and I cannot fix them all yet, sorry for that. 
v0.6 is coming soon with some fixes for stability, but it is hard to say if they are going to help everybody. 

One thing that might help is written down here: https://github.com/massclown/HalfSwordTrainerMod?tab=readme-ov-file#ue4ss-crashes-the-game: override the Unreal Engine version in UE4SS configuration
```
[EngineVersionOverride]
MajorVersion = 5
MinorVersion = 1
```

**Comment by Zeddikiel** [comment]
I checked the latest version 0.6, and while it is a lot more stable than it used to be, i still cant get past the first boss without the game crashing or stopping completely. you are doing great work, and I'd be happy to see this become more stable after the demo update. looking optimistic! you can dm me on discord @zeddikiel if you need any more help :)
