### ISSUE TITLE
Keybinds don't work

### ISSUE THREAD

**Issue by yeet554** [massclown/HalfSwordTrainerMod#4]
I downloaded the mod successfully at first. Turned it off and then on again and it no longer works. After installing it again my keybinds do not work. I can spawn stuff in If i click on the buttons but I can't use keybinds. If you have any idea how to fix this that'd be great.

**Comment by massclown** [comment]
Unfortunately sometimes keybinds don't work for me too, but a reboot solves it, usually. The mod uses UE4SS keybinds functionality in a fairly standard way.

**Comment by NoclipOZ** [comment]
> Unfortunately sometimes keybinds don't work for me too, but a reboot solves it, usually. The mod uses UE4SS keybinds functionality in a fairly standard way.

even after restarting multiple times the key binds still don't work

**Comment by massclown** [comment]
> > Unfortunately sometimes keybinds don't work for me too, but a reboot solves it, usually. The mod uses UE4SS keybinds functionality in a fairly standard way.
> 
> even after restarting multiple times the key binds still don't work
Could you post your `UE4SS.log` file here? It is in the same folder where you copied UE4SS, right next to the game executable `HalfSwordUE5-Win64-Shipping.exe`, etc.

**Comment by NoclipOZ** [comment]
> > > Unfortunately sometimes keybinds don't work for me too, but a reboot solves it, usually. The mod uses UE4SS keybinds functionality in a fairly standard way.
> > 
> > 
> > even after restarting multiple times the key binds still don't work
> 
> Did keybinds work for you in the beginning and then stopped working?
> 
> Could you post your `UE4SS.log` file here? It is in the same folder where you copied UE4SS, right next to the game executable `HalfSwordUE5-Win64-Shipping.exe`, etc.

i fixed it by redownloading it, if it ever happens again i will
