### ISSUE TITLE
Possess back to Original NPC doesn't work

### ISSUE THREAD

**Issue by CodeBatcher** [massclown/HalfSwordTrainerMod#7]
Im pressing Ctrl + Home but nothing happens

**Comment by massclown** [comment]
Does that happen always or sometimes? Do you see any errors in the log file (or in UE4SS console)?

**Comment by CodeBatcher** [comment]
> Does that happen always or sometimes? Do you see any errors in the log file (or in UE4SS console)?

oddly enough no

**Comment by massclown** [comment]
Thank you! Found the issue, it will be fixed in the next release of the mod (fix already in the repo, commit cfcee5efd4941759c03d04b95a29ebe5836ad6b8). TL;DR: the original Willie was cached way too early, it was often empty before the game set it to the correct one.
